### ISSUE TITLE
Functions and properties as comments

### ISSUE THREAD

**Issue by rimasinc** [heestand-xyz/SwiftUIOSC#1]
I'm trying to develop an app whose base I intend to make using SwiftUIOSC and AbletonOsc. I notice that there are several functions and properties that appear in OSC.swift as commented out and are not used in the actual code. Could someone explain to me why this is?

**Comment by heestand-xyz** [comment]
There was a plan to add support for receiving OSC, tho currently the package only sends OSC.

**Comment by heestand-xyz** [comment]
There has been a major update to the package now with more full support for OSC.
